package extension.editor.tabs.queryparams;

import extension.request.QueryParameters;

import javax.swing.*;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.util.List;

import static extension.editor.tabs.queryparams.QueryParamsTableColumn.queryParamsTableColumnsInOrder;
import static javax.swing.JTable.AUTO_RESIZE_OFF;

public class QueryParamsTab extends JPanel {

    public QueryParamsTab(QueryParameters queryParameters) {
        initComponents();

        QueryParamsTableModel queryParamsTableModel = new QueryParamsTableModel(queryParameters);
        queryParamsTable.setModel(queryParamsTableModel);
        queryParamsTable.setAutoResizeMode(AUTO_RESIZE_OFF);

        addComponentListener(new ComponentAdapter() {
            @Override
            public void componentResized(ComponentEvent e) {
                recalculateColumnWidths();
            }
        });
    }

    private void recalculateColumnWidths()
    {
        TableColumnModel tableColumnModel = queryParamsTable.getColumnModel();
        List<QueryParamsTableColumn> queryParamsTableColumns = queryParamsTableColumnsInOrder();
        int tableWidth = tableScrollPane.getWidth();

        queryParamsTableColumns.forEach(x -> {
            TableColumn tableColumn = tableColumnModel.getColumn(x.positionSortIndex);
            int columnWidth = Math.round(tableWidth * x.columnWidthPercentage);

            tableColumn.setPreferredWidth(columnWidth);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        tableScrollPane = new javax.swing.JScrollPane();
        queryParamsTable = new javax.swing.JTable();

        setLayout(new java.awt.GridBagLayout());

        tableScrollPane.setViewportView(queryParamsTable);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        add(tableScrollPane, gridBagConstraints);
    }// </editor-fold>


    // Variables declaration - do not modify
    private javax.swing.JTable queryParamsTable;
    private javax.swing.JScrollPane tableScrollPane;
    // End of variables declaration
}
