package extension.editor.tabs.queryparams;

public class QueryParamsActionsPanel extends javax.swing.JPanel {
    private final Runnable deleteSelectedQueryParamsAction;

    public QueryParamsActionsPanel(Runnable deleteSelectedQueryParamsAction) {
        this.deleteSelectedQueryParamsAction = deleteSelectedQueryParamsAction;

        initComponents();

        deleteButton.addActionListener((e) -> deleteSelectedQueryParamsAction.run());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        deleteButton = new javax.swing.JButton();
        moveUpButton = new javax.swing.JButton();
        moveDownButton = new javax.swing.JButton();

        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {0};
        layout.rowHeights = new int[] {0, 5, 0, 5, 0};
        setLayout(layout);

        deleteButton.setIcon(new javax.swing.ImageIcon("/Users/mike.eaton/burp-extensions/burpman/source/src/main/resources/images/outline_delete_black_24dp.png")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        add(deleteButton, gridBagConstraints);

        moveUpButton.setIcon(new javax.swing.ImageIcon("/Users/mike.eaton/burp-extensions/burpman/source/src/main/resources/images/outline_arrow_upward_black_24dp.png")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        add(moveUpButton, gridBagConstraints);

        moveDownButton.setIcon(new javax.swing.ImageIcon("/Users/mike.eaton/burp-extensions/burpman/source/src/main/resources/images/outline_arrow_downward_black_24dp.png")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        add(moveDownButton, gridBagConstraints);
    }// </editor-fold>


    // Variables declaration - do not modify
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton moveDownButton;
    private javax.swing.JButton moveUpButton;
    // End of variables declaration
}
