/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package extension.editor;

import extension.editor.tabs.queryparams.QueryParamsTab;
import extension.request.Method;
import extension.request.RequestModel;
import mvc.ViewController;
import mvc.updatestrategies.ComboBoxUpdateStrategy;
import mvc.updatestrategies.ComponentUpdateStrategies;
import mvc.updatestrategies.TextFieldUpdateStrategy;

import javax.swing.*;

import static extension.request.RequestModelProperties.METHOD;
import static extension.request.RequestModelProperties.PATH;

public class BurpmanEditor extends JPanel implements ViewController {
    private final ComponentUpdateStrategies componentUpdateStrategies;
    private final RequestModel requestModel;

    public BurpmanEditor(RequestModel requestModel) {
        this.requestModel = requestModel;

        initComponents();

        this.componentUpdateStrategies = new ComponentUpdateStrategies();
        initComponentUpdateStrategies();

        configureMethodComboBox();
    }

    private void configureMethodComboBox() {
        DefaultComboBoxModel<Method> comboBoxModel = new DefaultComboBoxModel<>(Method.values());
        methodComboBox.setModel(comboBoxModel);
    }

    private void initComponentUpdateStrategies() {
        TextFieldUpdateStrategy textFieldUpdateStrategy = new TextFieldUpdateStrategy(PATH.getPropertyName(), pathTextField);
        componentUpdateStrategies.addStrategy(textFieldUpdateStrategy);

        ComboBoxUpdateStrategy<Method> comboBoxUpdateStrategy = new ComboBoxUpdateStrategy<>(METHOD.getPropertyName(), methodComboBox);
        componentUpdateStrategies.addStrategy(comboBoxUpdateStrategy);
    }

    @Override
    public ComponentUpdateStrategies getComponentUpdateStrategies() {
        return componentUpdateStrategies;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        contentPanel = new javax.swing.JPanel();
        methodComboBox = new javax.swing.JComboBox<>();
        pathTextField = new javax.swing.JTextField();
        requestAttributesTabbedPane = new javax.swing.JTabbedPane();
        queryParamsTab = new QueryParamsTab(requestModel.getQueryParameters());

        setLayout(new java.awt.GridBagLayout());

        contentPanel.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        contentPanel.add(methodComboBox, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        contentPanel.add(pathTextField, gridBagConstraints);

        requestAttributesTabbedPane.addTab("Query Params", queryParamsTab);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        contentPanel.add(requestAttributesTabbedPane, gridBagConstraints);
        requestAttributesTabbedPane.getAccessibleContext().setAccessibleName("Request Metadata tabs");

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(contentPanel, gridBagConstraints);
    }// </editor-fold>


    // Variables declaration - do not modify
    private javax.swing.JPanel contentPanel;
    private javax.swing.JComboBox<Method> methodComboBox;
    private javax.swing.JTextField pathTextField;
    private QueryParamsTab queryParamsTab;
    private javax.swing.JTabbedPane requestAttributesTabbedPane;
    // End of variables declaration
}
